### ISSUE TITLE
日历组件改成横向显示的mode之后，底部会有很大的空白区域

### ISSUE THREAD

**Issue by jameszhanc** [webkixi/aotoo-xquery#2]

**Comment by webkixi** [comment]
你可以根据需求，自行调整样式，demo里面都是基本样式

**Comment by webkixi** [comment]
> _No description provided._

你可以根据需求，自行调整样式，demo里面都是基本样式

**Comment by webkixi** [comment]
> _No description provided._

你可以根据需求，自行调整样式，demo里面都是基本样式
